### ISSUE TITLE
Update "cap" to "att" in JWT structure, proofs section

### ISSUE THREAD

**Issue by bgins** [fission-codes/whitepaper#4]
In the JWT Structure section of the guide, the proofs section (https://github.com/fission-suite/whitepaper/blob/master/access-control/ucan/jwt-authentication.md#proofs) says

> Each proof MUST form a chain all the way back to the resource originator / owner. If a UCAN's proof list is empty, it is read as being the initial/"root" UCAN. In this case, the ”iss” is the resource originator / owner for everything in the “cap” section.

Should "cap" be "att"? Each `att` defines capabilities (`cap`) over resources, and maybe this just needs to be reworded a bit?

**Comment by expede** [comment]
Fixed!

> Each proof MUST form a chain all the way back to the resource originator / owner. If a UCAN's proof list is empty, it is read as being the initial/"root" UCAN. In this case, the ”iss” is the resource originator / owner for everything in the “att” section.
